// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    sov_dcdt_safe
    (
        init => init
        upgrade => upgrade
        updateConfiguration => update_configuration
        setFeeMarketAddress => set_fee_market_address
        setMaxBridgedAmount => set_max_bridged_amount
        deposit => deposit
        getNativeToken => native_token
        getMaxBridgedAmount => max_bridged_amount
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
