// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    header_verifier
    (
        init => init
        upgrade => upgrade
        registerBlsPubKeys => register_bls_pub_keys
        registerBridgeOps => register_bridge_operations
        changeValidatorSet => change_validator_set
        setDcdtSafeAddress => set_dcdt_safe_address
        removeExecutedHash => remove_executed_hash
        lockOperationHash => lock_operation_hash
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
