// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    fee_market
    (
        init => init
        upgrade => upgrade
        setPriceAggregatorAddress => set_price_aggregator_address
        setFee => set_fee
        removeFee => remove_fee
        getTokenFee => token_fee
        addUsersToWhitelist => add_users_to_whitelist
        removeUsersFromWhitelist => remove_users_from_whitelist
        distributeFees => distribute_fees
        subtractFee => subtract_fee
        getUsersWhitelist => users_whitelist
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
